/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface PerpetualContract extends Truffle.Contract<PerpetualInstance> {
  "new"(
    params: {
      withdrawalLiveness: number | BN | string;
      configStoreAddress: string;
      collateralAddress: string;
      tokenAddress: string;
      finderAddress: string;
      timerAddress: string;
      priceFeedIdentifier: string;
      fundingRateIdentifier: string;
      minSponsorTokens: { rawValue: number | BN | string };
      tokenScaling: { rawValue: number | BN | string };
      liquidationLiveness: number | BN | string;
      collateralRequirement: { rawValue: number | BN | string };
      disputeBondPercentage: { rawValue: number | BN | string };
      sponsorDisputeRewardPercentage: { rawValue: number | BN | string };
      disputerDisputeRewardPercentage: { rawValue: number | BN | string };
    },
    meta?: Truffle.TransactionDetails
  ): Promise<PerpetualInstance>;
}

export interface Deposit {
  name: "Deposit";
  args: {
    sponsor: string;
    collateralAmount: BN;
    0: string;
    1: BN;
  };
}

export interface DisputeSettled {
  name: "DisputeSettled";
  args: {
    caller: string;
    sponsor: string;
    liquidator: string;
    disputer: string;
    liquidationId: BN;
    disputeSucceeded: boolean;
    0: string;
    1: string;
    2: string;
    3: string;
    4: BN;
    5: boolean;
  };
}

export interface EmergencyShutdown {
  name: "EmergencyShutdown";
  args: {
    caller: string;
    shutdownTimestamp: BN;
    0: string;
    1: BN;
  };
}

export interface EndedSponsorPosition {
  name: "EndedSponsorPosition";
  args: {
    sponsor: string;
    0: string;
  };
}

export interface FinalFeesPaid {
  name: "FinalFeesPaid";
  args: {
    amount: BN;
    0: BN;
  };
}

export interface FundingRateUpdated {
  name: "FundingRateUpdated";
  args: {
    newFundingRate: BN;
    updateTime: BN;
    reward: BN;
    0: BN;
    1: BN;
    2: BN;
  };
}

export interface LiquidationCreated {
  name: "LiquidationCreated";
  args: {
    sponsor: string;
    liquidator: string;
    liquidationId: BN;
    tokensOutstanding: BN;
    lockedCollateral: BN;
    liquidatedCollateral: BN;
    liquidationTime: BN;
    0: string;
    1: string;
    2: BN;
    3: BN;
    4: BN;
    5: BN;
    6: BN;
  };
}

export interface LiquidationDisputed {
  name: "LiquidationDisputed";
  args: {
    sponsor: string;
    liquidator: string;
    disputer: string;
    liquidationId: BN;
    disputeBondAmount: BN;
    0: string;
    1: string;
    2: string;
    3: BN;
    4: BN;
  };
}

export interface LiquidationWithdrawn {
  name: "LiquidationWithdrawn";
  args: {
    caller: string;
    paidToLiquidator: BN;
    paidToDisputer: BN;
    paidToSponsor: BN;
    liquidationStatus: BN;
    settlementPrice: BN;
    0: string;
    1: BN;
    2: BN;
    3: BN;
    4: BN;
    5: BN;
  };
}

export interface NewSponsor {
  name: "NewSponsor";
  args: {
    sponsor: string;
    0: string;
  };
}

export interface PositionCreated {
  name: "PositionCreated";
  args: {
    sponsor: string;
    collateralAmount: BN;
    tokenAmount: BN;
    0: string;
    1: BN;
    2: BN;
  };
}

export interface Redeem {
  name: "Redeem";
  args: {
    sponsor: string;
    collateralAmount: BN;
    tokenAmount: BN;
    0: string;
    1: BN;
    2: BN;
  };
}

export interface RegularFeesPaid {
  name: "RegularFeesPaid";
  args: {
    regularFee: BN;
    lateFee: BN;
    0: BN;
    1: BN;
  };
}

export interface Repay {
  name: "Repay";
  args: {
    sponsor: string;
    numTokensRepaid: BN;
    newTokenCount: BN;
    0: string;
    1: BN;
    2: BN;
  };
}

export interface RequestWithdrawal {
  name: "RequestWithdrawal";
  args: {
    sponsor: string;
    collateralAmount: BN;
    0: string;
    1: BN;
  };
}

export interface RequestWithdrawalCanceled {
  name: "RequestWithdrawalCanceled";
  args: {
    sponsor: string;
    collateralAmount: BN;
    0: string;
    1: BN;
  };
}

export interface RequestWithdrawalExecuted {
  name: "RequestWithdrawalExecuted";
  args: {
    sponsor: string;
    collateralAmount: BN;
    0: string;
    1: BN;
  };
}

export interface SettleEmergencyShutdown {
  name: "SettleEmergencyShutdown";
  args: {
    caller: string;
    collateralReturned: BN;
    tokensBurned: BN;
    0: string;
    1: BN;
    2: BN;
  };
}

export interface Withdrawal {
  name: "Withdrawal";
  args: {
    sponsor: string;
    collateralAmount: BN;
    0: string;
    1: BN;
  };
}

type AllEvents =
  | Deposit
  | DisputeSettled
  | EmergencyShutdown
  | EndedSponsorPosition
  | FinalFeesPaid
  | FundingRateUpdated
  | LiquidationCreated
  | LiquidationDisputed
  | LiquidationWithdrawn
  | NewSponsor
  | PositionCreated
  | Redeem
  | RegularFeesPaid
  | Repay
  | RequestWithdrawal
  | RequestWithdrawalCanceled
  | RequestWithdrawalExecuted
  | SettleEmergencyShutdown
  | Withdrawal;

export interface PerpetualInstance extends Truffle.ContractInstance {
  /**
   * This method takes 3 distinct actions: 1. Pays out regular fees. 2. If possible, resolves the outstanding funding rate proposal, pulling the result in and paying out the rewards. 3. Applies the prevailing funding rate over the most recent period.
   */
  applyFundingRate: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  /**
   * Cancels a pending withdrawal request.
   */
  cancelWithdrawal: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  collateralCurrency(txDetails?: Truffle.TransactionDetails): Promise<string>;

  collateralRequirement(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  configStore(txDetails?: Truffle.TransactionDetails): Promise<string>;

  create: {
    (
      collateralAmount: { rawValue: number | BN | string },
      numTokens: { rawValue: number | BN | string },
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      collateralAmount: { rawValue: number | BN | string },
      numTokens: { rawValue: number | BN | string },
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      collateralAmount: { rawValue: number | BN | string },
      numTokens: { rawValue: number | BN | string },
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      collateralAmount: { rawValue: number | BN | string },
      numTokens: { rawValue: number | BN | string },
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  createLiquidation: {
    (
      sponsor: string,
      minCollateralPerToken: { rawValue: number | BN | string },
      maxCollateralPerToken: { rawValue: number | BN | string },
      maxTokensToLiquidate: { rawValue: number | BN | string },
      deadline: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      sponsor: string,
      minCollateralPerToken: { rawValue: number | BN | string },
      maxCollateralPerToken: { rawValue: number | BN | string },
      maxTokensToLiquidate: { rawValue: number | BN | string },
      deadline: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: BN; 1: { rawValue: BN }; 2: { rawValue: BN } }>;
    sendTransaction(
      sponsor: string,
      minCollateralPerToken: { rawValue: number | BN | string },
      maxCollateralPerToken: { rawValue: number | BN | string },
      maxTokensToLiquidate: { rawValue: number | BN | string },
      deadline: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      sponsor: string,
      minCollateralPerToken: { rawValue: number | BN | string },
      maxCollateralPerToken: { rawValue: number | BN | string },
      maxTokensToLiquidate: { rawValue: number | BN | string },
      deadline: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  cumulativeFeeMultiplier(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  deposit: {
    (
      collateralAmount: { rawValue: number | BN | string },
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      collateralAmount: { rawValue: number | BN | string },
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      collateralAmount: { rawValue: number | BN | string },
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      collateralAmount: { rawValue: number | BN | string },
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  depositTo: {
    (
      sponsor: string,
      collateralAmount: { rawValue: number | BN | string },
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      sponsor: string,
      collateralAmount: { rawValue: number | BN | string },
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      sponsor: string,
      collateralAmount: { rawValue: number | BN | string },
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      sponsor: string,
      collateralAmount: { rawValue: number | BN | string },
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Can only dispute a liquidation before the liquidation expires and if there are no other pending disputes. This contract must be approved to spend at least the dispute bond amount of `collateralCurrency`. This dispute bond amount is calculated from `disputeBondPercentage` times the collateral in the liquidation.
   * Disputes a liquidation, if the caller has enough collateral to post a dispute bond and pay a fixed final fee charged on each price request.
   * @param liquidationId of the disputed liquidation.
   * @param sponsor the address of the sponsor whose liquidation is being disputed.
   */
  dispute: {
    (
      liquidationId: number | BN | string,
      sponsor: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      liquidationId: number | BN | string,
      sponsor: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ rawValue: BN }>;
    sendTransaction(
      liquidationId: number | BN | string,
      sponsor: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      liquidationId: number | BN | string,
      sponsor: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  disputeBondPercentage(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  disputerDisputeRewardPercentage(
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  /**
   * Only the governor can call this function as they are permissioned within the `FinancialContractAdmin`. Upon emergency shutdown, the contract settlement time is set to the shutdown time. This enables withdrawal to occur via the `settleEmergencyShutdown` function.
   * Premature contract settlement under emergency circumstances.
   */
  emergencyShutdown: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  emergencyShutdownPrice(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  emergencyShutdownTimestamp(
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  finder(txDetails?: Truffle.TransactionDetails): Promise<string>;

  fundingRate(
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    0: { rawValue: BN };
    1: string;
    2: { rawValue: BN };
    3: BN;
    4: BN;
    5: BN;
  }>;

  /**
   * This is necessary because the struct returned by the positions() method shows rawCollateral, which isn't a user-readable value.This method accounts for pending regular fees that have not yet been withdrawn from this contract, for example if the `lastPaymentTime != currentTime`.
   * Accessor method for a sponsor's collateral.
   * @param sponsor address whose collateral amount is retrieved.
   */
  getCollateral(
    sponsor: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ rawValue: BN }>;

  /**
   * Gets the current time. Will return the last time set in `setCurrentTime` if running in test mode. Otherwise, it will return the block timestamp.
   */
  getCurrentTime(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  getFundingRateAppliedTokenDebt(
    rawTokenDebt: { rawValue: number | BN | string },
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ rawValue: BN }>;

  /**
   * Gets all liquidation information for a given sponsor address.
   * @param sponsor address of the position sponsor.
   */
  getLiquidations(
    sponsor: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<
    {
      sponsor: string;
      liquidator: string;
      state: BN;
      liquidationTime: BN;
      tokensOutstanding: { rawValue: BN };
      lockedCollateral: { rawValue: BN };
      liquidatedCollateral: { rawValue: BN };
      rawUnitCollateral: { rawValue: BN };
      disputer: string;
      settlementPrice: { rawValue: BN };
      finalFee: { rawValue: BN };
    }[]
  >;

  /**
   * This returns 0 and exit early if there is no pfc, fees were already paid during the current block, or the fee rate is 0.
   * Fetch any regular fees that the contract has pending but has not yet paid. If the fees to be paid are more than the total collateral within the contract then the totalPaid returned is full contract collateral amount.
   */
  getOutstandingRegularFees(
    time: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: { rawValue: BN }; 1: { rawValue: BN }; 2: { rawValue: BN } }>;

  /**
   * Multiplying the `cumulativeFeeMultiplier` by the ratio of non-PfC-collateral :: PfC-collateral effectively pays all sponsors a pro-rata portion of the excess collateral.This will revert if PfC is 0 and this contract's collateral balance > 0.
   * Removes excess collateral balance not counted in the PfC by distributing it out pro-rata to all sponsors.
   */
  gulp: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  liquidationLiveness(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  liquidations(
    arg0: string,
    arg1: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    0: string;
    1: string;
    2: BN;
    3: BN;
    4: { rawValue: BN };
    5: { rawValue: BN };
    6: { rawValue: BN };
    7: { rawValue: BN };
    8: string;
    9: { rawValue: BN };
    10: { rawValue: BN };
  }>;

  minSponsorTokens(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  /**
   * These must be paid periodically for the life of the contract. If the contract has not paid its regular fee in a week or more then a late penalty is applied which is sent to the caller. If the amount of fees owed are greater than the pfc, then this will pay as much as possible from the available collateral. An event is only fired if the fees charged are greater than 0.
   * Pays UMA DVM regular fees (as a % of the collateral pool) to the Store contract.
   */
  payRegularFees: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<{ rawValue: BN }>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  /**
   * This is equivalent to the collateral pool available from which to pay fees. Therefore, derived contracts are expected to implement this so that pay-fee methods can correctly compute the owed fees as a % of PfC.
   * Gets the current profit from corruption for this contract in terms of the collateral currency.
   */
  pfc(txDetails?: Truffle.TransactionDetails): Promise<{ rawValue: BN }>;

  positions(
    arg0: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    0: { rawValue: BN };
    1: BN;
    2: { rawValue: BN };
    3: { rawValue: BN };
  }>;

  priceIdentifier(txDetails?: Truffle.TransactionDetails): Promise<string>;

  proposeFundingRate: {
    (
      rate: { rawValue: number | BN | string },
      timestamp: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      rate: { rawValue: number | BN | string },
      timestamp: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ rawValue: BN }>;
    sendTransaction(
      rate: { rawValue: number | BN | string },
      timestamp: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      rate: { rawValue: number | BN | string },
      timestamp: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  rawLiquidationCollateral(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  rawTotalPositionCollateral(
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  redeem: {
    (
      numTokens: { rawValue: number | BN | string },
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      numTokens: { rawValue: number | BN | string },
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ rawValue: BN }>;
    sendTransaction(
      numTokens: { rawValue: number | BN | string },
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      numTokens: { rawValue: number | BN | string },
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * This is supposed to be implemented by any contract that inherits `AdministrateeInterface` and callable only by the Governor contract. This method is therefore minimally implemented in this contract and does nothing.
   * Theoretically supposed to pay fees and move money between margin accounts to make sure they reflect the NAV of the contract. However, this functionality doesn't apply to this contract.
   */
  remargin: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  repay: {
    (
      numTokens: { rawValue: number | BN | string },
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      numTokens: { rawValue: number | BN | string },
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      numTokens: { rawValue: number | BN | string },
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      numTokens: { rawValue: number | BN | string },
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  requestWithdrawal: {
    (
      collateralAmount: { rawValue: number | BN | string },
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      collateralAmount: { rawValue: number | BN | string },
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      collateralAmount: { rawValue: number | BN | string },
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      collateralAmount: { rawValue: number | BN | string },
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Will revert if not running in test mode.
   * Sets the current time.
   * @param time timestamp to set current Testable time to.
   */
  setCurrentTime: {
    (
      time: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      time: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      time: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      time: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * This burns all tokens from the caller of `tokenCurrency` and sends back the resolved settlement value of `collateralCurrency`. Might not redeem the full proportional amount of collateral in order to account for precision loss. This contract must be approved to spend `tokenCurrency` at least up to the caller's full balance.This contract must have the Burner role for the `tokenCurrency`.Note that this function does not call the updateFundingRate modifier to update the funding rate as this function is only called after an emergency shutdown & there should be no funding rate updates after the shutdown.
   * If the contract is emergency shutdown then all token holders and sponsors can redeem their tokens or remaining collateral for underlying at the prevailing price defined by a DVM vote.
   */
  settleEmergencyShutdown: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<{ rawValue: BN }>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  sponsorDisputeRewardPercentage(
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  timerAddress(txDetails?: Truffle.TransactionDetails): Promise<string>;

  tokenCurrency(txDetails?: Truffle.TransactionDetails): Promise<string>;

  /**
   * Accessor method for the total collateral stored within the PerpetualPositionManager.
   */
  totalPositionCollateral(
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ rawValue: BN }>;

  totalTokensOutstanding(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  withdraw: {
    (
      collateralAmount: { rawValue: number | BN | string },
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      collateralAmount: { rawValue: number | BN | string },
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ rawValue: BN }>;
    sendTransaction(
      collateralAmount: { rawValue: number | BN | string },
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      collateralAmount: { rawValue: number | BN | string },
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * If the dispute SUCCEEDED: the sponsor, liquidator, and disputer are eligible for payment. If the dispute FAILED: only the liquidator receives payment. This method deletes the liquidation data. This method will revert if rewards have already been dispersed.
   * After a dispute has settled or after a non-disputed liquidation has expired, anyone can call this method to disperse payments to the sponsor, liquidator, and disputer.
   * @param liquidationId uniquely identifies the sponsor's liquidation.
   * @param sponsor address of the sponsor associated with the liquidation.
   */
  withdrawLiquidation: {
    (
      liquidationId: number | BN | string,
      sponsor: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      liquidationId: number | BN | string,
      sponsor: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      payToSponsor: { rawValue: BN };
      payToLiquidator: { rawValue: BN };
      payToDisputer: { rawValue: BN };
      paidToSponsor: { rawValue: BN };
      paidToLiquidator: { rawValue: BN };
      paidToDisputer: { rawValue: BN };
    }>;
    sendTransaction(
      liquidationId: number | BN | string,
      sponsor: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      liquidationId: number | BN | string,
      sponsor: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Might not withdraw the full requested amount in order to account for precision loss or if the full requested amount exceeds the collateral in the position (due to paying fees).
   * After a passed withdrawal request (i.e., by a call to `requestWithdrawal` and waiting `withdrawalLiveness`), withdraws `positionData.withdrawalRequestAmount` of collateral currency.
   */
  withdrawPassedRequest: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<{ rawValue: BN }>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  withdrawalLiveness(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  methods: {
    /**
     * This method takes 3 distinct actions: 1. Pays out regular fees. 2. If possible, resolves the outstanding funding rate proposal, pulling the result in and paying out the rewards. 3. Applies the prevailing funding rate over the most recent period.
     */
    applyFundingRate: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    /**
     * Cancels a pending withdrawal request.
     */
    cancelWithdrawal: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    collateralCurrency(txDetails?: Truffle.TransactionDetails): Promise<string>;

    collateralRequirement(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    configStore(txDetails?: Truffle.TransactionDetails): Promise<string>;

    create: {
      (
        collateralAmount: { rawValue: number | BN | string },
        numTokens: { rawValue: number | BN | string },
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        collateralAmount: { rawValue: number | BN | string },
        numTokens: { rawValue: number | BN | string },
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        collateralAmount: { rawValue: number | BN | string },
        numTokens: { rawValue: number | BN | string },
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        collateralAmount: { rawValue: number | BN | string },
        numTokens: { rawValue: number | BN | string },
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    createLiquidation: {
      (
        sponsor: string,
        minCollateralPerToken: { rawValue: number | BN | string },
        maxCollateralPerToken: { rawValue: number | BN | string },
        maxTokensToLiquidate: { rawValue: number | BN | string },
        deadline: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        sponsor: string,
        minCollateralPerToken: { rawValue: number | BN | string },
        maxCollateralPerToken: { rawValue: number | BN | string },
        maxTokensToLiquidate: { rawValue: number | BN | string },
        deadline: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<{ 0: BN; 1: { rawValue: BN }; 2: { rawValue: BN } }>;
      sendTransaction(
        sponsor: string,
        minCollateralPerToken: { rawValue: number | BN | string },
        maxCollateralPerToken: { rawValue: number | BN | string },
        maxTokensToLiquidate: { rawValue: number | BN | string },
        deadline: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        sponsor: string,
        minCollateralPerToken: { rawValue: number | BN | string },
        maxCollateralPerToken: { rawValue: number | BN | string },
        maxTokensToLiquidate: { rawValue: number | BN | string },
        deadline: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    cumulativeFeeMultiplier(
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    deposit: {
      (
        collateralAmount: { rawValue: number | BN | string },
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        collateralAmount: { rawValue: number | BN | string },
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        collateralAmount: { rawValue: number | BN | string },
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        collateralAmount: { rawValue: number | BN | string },
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    depositTo: {
      (
        sponsor: string,
        collateralAmount: { rawValue: number | BN | string },
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        sponsor: string,
        collateralAmount: { rawValue: number | BN | string },
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        sponsor: string,
        collateralAmount: { rawValue: number | BN | string },
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        sponsor: string,
        collateralAmount: { rawValue: number | BN | string },
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Can only dispute a liquidation before the liquidation expires and if there are no other pending disputes. This contract must be approved to spend at least the dispute bond amount of `collateralCurrency`. This dispute bond amount is calculated from `disputeBondPercentage` times the collateral in the liquidation.
     * Disputes a liquidation, if the caller has enough collateral to post a dispute bond and pay a fixed final fee charged on each price request.
     * @param liquidationId of the disputed liquidation.
     * @param sponsor the address of the sponsor whose liquidation is being disputed.
     */
    dispute: {
      (
        liquidationId: number | BN | string,
        sponsor: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        liquidationId: number | BN | string,
        sponsor: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<{ rawValue: BN }>;
      sendTransaction(
        liquidationId: number | BN | string,
        sponsor: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        liquidationId: number | BN | string,
        sponsor: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    disputeBondPercentage(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    disputerDisputeRewardPercentage(
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    /**
     * Only the governor can call this function as they are permissioned within the `FinancialContractAdmin`. Upon emergency shutdown, the contract settlement time is set to the shutdown time. This enables withdrawal to occur via the `settleEmergencyShutdown` function.
     * Premature contract settlement under emergency circumstances.
     */
    emergencyShutdown: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    emergencyShutdownPrice(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    emergencyShutdownTimestamp(
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    finder(txDetails?: Truffle.TransactionDetails): Promise<string>;

    fundingRate(
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      0: { rawValue: BN };
      1: string;
      2: { rawValue: BN };
      3: BN;
      4: BN;
      5: BN;
    }>;

    /**
     * This is necessary because the struct returned by the positions() method shows rawCollateral, which isn't a user-readable value.This method accounts for pending regular fees that have not yet been withdrawn from this contract, for example if the `lastPaymentTime != currentTime`.
     * Accessor method for a sponsor's collateral.
     * @param sponsor address whose collateral amount is retrieved.
     */
    getCollateral(
      sponsor: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ rawValue: BN }>;

    /**
     * Gets the current time. Will return the last time set in `setCurrentTime` if running in test mode. Otherwise, it will return the block timestamp.
     */
    getCurrentTime(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    getFundingRateAppliedTokenDebt(
      rawTokenDebt: { rawValue: number | BN | string },
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ rawValue: BN }>;

    /**
     * Gets all liquidation information for a given sponsor address.
     * @param sponsor address of the position sponsor.
     */
    getLiquidations(
      sponsor: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<
      {
        sponsor: string;
        liquidator: string;
        state: BN;
        liquidationTime: BN;
        tokensOutstanding: { rawValue: BN };
        lockedCollateral: { rawValue: BN };
        liquidatedCollateral: { rawValue: BN };
        rawUnitCollateral: { rawValue: BN };
        disputer: string;
        settlementPrice: { rawValue: BN };
        finalFee: { rawValue: BN };
      }[]
    >;

    /**
     * This returns 0 and exit early if there is no pfc, fees were already paid during the current block, or the fee rate is 0.
     * Fetch any regular fees that the contract has pending but has not yet paid. If the fees to be paid are more than the total collateral within the contract then the totalPaid returned is full contract collateral amount.
     */
    getOutstandingRegularFees(
      time: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      0: { rawValue: BN };
      1: { rawValue: BN };
      2: { rawValue: BN };
    }>;

    /**
     * Multiplying the `cumulativeFeeMultiplier` by the ratio of non-PfC-collateral :: PfC-collateral effectively pays all sponsors a pro-rata portion of the excess collateral.This will revert if PfC is 0 and this contract's collateral balance > 0.
     * Removes excess collateral balance not counted in the PfC by distributing it out pro-rata to all sponsors.
     */
    gulp: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    liquidationLiveness(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    liquidations(
      arg0: string,
      arg1: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      0: string;
      1: string;
      2: BN;
      3: BN;
      4: { rawValue: BN };
      5: { rawValue: BN };
      6: { rawValue: BN };
      7: { rawValue: BN };
      8: string;
      9: { rawValue: BN };
      10: { rawValue: BN };
    }>;

    minSponsorTokens(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    /**
     * These must be paid periodically for the life of the contract. If the contract has not paid its regular fee in a week or more then a late penalty is applied which is sent to the caller. If the amount of fees owed are greater than the pfc, then this will pay as much as possible from the available collateral. An event is only fired if the fees charged are greater than 0.
     * Pays UMA DVM regular fees (as a % of the collateral pool) to the Store contract.
     */
    payRegularFees: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<{ rawValue: BN }>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    /**
     * This is equivalent to the collateral pool available from which to pay fees. Therefore, derived contracts are expected to implement this so that pay-fee methods can correctly compute the owed fees as a % of PfC.
     * Gets the current profit from corruption for this contract in terms of the collateral currency.
     */
    pfc(txDetails?: Truffle.TransactionDetails): Promise<{ rawValue: BN }>;

    positions(
      arg0: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      0: { rawValue: BN };
      1: BN;
      2: { rawValue: BN };
      3: { rawValue: BN };
    }>;

    priceIdentifier(txDetails?: Truffle.TransactionDetails): Promise<string>;

    proposeFundingRate: {
      (
        rate: { rawValue: number | BN | string },
        timestamp: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        rate: { rawValue: number | BN | string },
        timestamp: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<{ rawValue: BN }>;
      sendTransaction(
        rate: { rawValue: number | BN | string },
        timestamp: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        rate: { rawValue: number | BN | string },
        timestamp: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    rawLiquidationCollateral(
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    rawTotalPositionCollateral(
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    redeem: {
      (
        numTokens: { rawValue: number | BN | string },
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        numTokens: { rawValue: number | BN | string },
        txDetails?: Truffle.TransactionDetails
      ): Promise<{ rawValue: BN }>;
      sendTransaction(
        numTokens: { rawValue: number | BN | string },
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        numTokens: { rawValue: number | BN | string },
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * This is supposed to be implemented by any contract that inherits `AdministrateeInterface` and callable only by the Governor contract. This method is therefore minimally implemented in this contract and does nothing.
     * Theoretically supposed to pay fees and move money between margin accounts to make sure they reflect the NAV of the contract. However, this functionality doesn't apply to this contract.
     */
    remargin: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    repay: {
      (
        numTokens: { rawValue: number | BN | string },
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        numTokens: { rawValue: number | BN | string },
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        numTokens: { rawValue: number | BN | string },
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        numTokens: { rawValue: number | BN | string },
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    requestWithdrawal: {
      (
        collateralAmount: { rawValue: number | BN | string },
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        collateralAmount: { rawValue: number | BN | string },
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        collateralAmount: { rawValue: number | BN | string },
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        collateralAmount: { rawValue: number | BN | string },
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Will revert if not running in test mode.
     * Sets the current time.
     * @param time timestamp to set current Testable time to.
     */
    setCurrentTime: {
      (
        time: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        time: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        time: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        time: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * This burns all tokens from the caller of `tokenCurrency` and sends back the resolved settlement value of `collateralCurrency`. Might not redeem the full proportional amount of collateral in order to account for precision loss. This contract must be approved to spend `tokenCurrency` at least up to the caller's full balance.This contract must have the Burner role for the `tokenCurrency`.Note that this function does not call the updateFundingRate modifier to update the funding rate as this function is only called after an emergency shutdown & there should be no funding rate updates after the shutdown.
     * If the contract is emergency shutdown then all token holders and sponsors can redeem their tokens or remaining collateral for underlying at the prevailing price defined by a DVM vote.
     */
    settleEmergencyShutdown: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<{ rawValue: BN }>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    sponsorDisputeRewardPercentage(
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    timerAddress(txDetails?: Truffle.TransactionDetails): Promise<string>;

    tokenCurrency(txDetails?: Truffle.TransactionDetails): Promise<string>;

    /**
     * Accessor method for the total collateral stored within the PerpetualPositionManager.
     */
    totalPositionCollateral(
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ rawValue: BN }>;

    totalTokensOutstanding(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    withdraw: {
      (
        collateralAmount: { rawValue: number | BN | string },
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        collateralAmount: { rawValue: number | BN | string },
        txDetails?: Truffle.TransactionDetails
      ): Promise<{ rawValue: BN }>;
      sendTransaction(
        collateralAmount: { rawValue: number | BN | string },
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        collateralAmount: { rawValue: number | BN | string },
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * If the dispute SUCCEEDED: the sponsor, liquidator, and disputer are eligible for payment. If the dispute FAILED: only the liquidator receives payment. This method deletes the liquidation data. This method will revert if rewards have already been dispersed.
     * After a dispute has settled or after a non-disputed liquidation has expired, anyone can call this method to disperse payments to the sponsor, liquidator, and disputer.
     * @param liquidationId uniquely identifies the sponsor's liquidation.
     * @param sponsor address of the sponsor associated with the liquidation.
     */
    withdrawLiquidation: {
      (
        liquidationId: number | BN | string,
        sponsor: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        liquidationId: number | BN | string,
        sponsor: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<{
        payToSponsor: { rawValue: BN };
        payToLiquidator: { rawValue: BN };
        payToDisputer: { rawValue: BN };
        paidToSponsor: { rawValue: BN };
        paidToLiquidator: { rawValue: BN };
        paidToDisputer: { rawValue: BN };
      }>;
      sendTransaction(
        liquidationId: number | BN | string,
        sponsor: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        liquidationId: number | BN | string,
        sponsor: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Might not withdraw the full requested amount in order to account for precision loss or if the full requested amount exceeds the collateral in the position (due to paying fees).
     * After a passed withdrawal request (i.e., by a call to `requestWithdrawal` and waiting `withdrawalLiveness`), withdraws `positionData.withdrawalRequestAmount` of collateral currency.
     */
    withdrawPassedRequest: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<{ rawValue: BN }>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    withdrawalLiveness(txDetails?: Truffle.TransactionDetails): Promise<BN>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
