/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface IFxMessageProcessorContract
  extends Truffle.Contract<IFxMessageProcessorInstance> {
  "new"(
    meta?: Truffle.TransactionDetails
  ): Promise<IFxMessageProcessorInstance>;
}

type AllEvents = never;

export interface IFxMessageProcessorInstance extends Truffle.ContractInstance {
  processMessageFromRoot: {
    (
      stateId: number | BN | string,
      rootMessageSender: string,
      data: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      stateId: number | BN | string,
      rootMessageSender: string,
      data: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      stateId: number | BN | string,
      rootMessageSender: string,
      data: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      stateId: number | BN | string,
      rootMessageSender: string,
      data: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    processMessageFromRoot: {
      (
        stateId: number | BN | string,
        rootMessageSender: string,
        data: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        stateId: number | BN | string,
        rootMessageSender: string,
        data: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        stateId: number | BN | string,
        rootMessageSender: string,
        data: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        stateId: number | BN | string,
        rootMessageSender: string,
        data: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
