/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface SinkOracleContract
  extends Truffle.Contract<SinkOracleInstance> {
  "new"(
    _finderAddress: string,
    _chainID: number | BN | string,
    _destinationChainID: number | BN | string,
    meta?: Truffle.TransactionDetails
  ): Promise<SinkOracleInstance>;
}

export interface PriceRequestAdded {
  name: "PriceRequestAdded";
  args: {
    chainID: BN;
    identifier: string;
    time: BN;
    ancillaryData: string;
    0: BN;
    1: string;
    2: BN;
    3: string;
  };
}

export interface PushedPrice {
  name: "PushedPrice";
  args: {
    chainID: BN;
    identifier: string;
    time: BN;
    ancillaryData: string;
    price: BN;
    0: BN;
    1: string;
    2: BN;
    3: string;
    4: BN;
  };
}

type AllEvents = PriceRequestAdded | PushedPrice;

export interface SinkOracleInstance extends Truffle.ContractInstance {
  currentChainID(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  destinationChainID(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  finder(txDetails?: Truffle.TransactionDetails): Promise<string>;

  /**
   * Can be called only by a Registered contract that is allowed to make DVM price requests. Will mark this price request as Requested, and therefore able to receive the ultimate price resolution data, and also calls the local Bridge's deposit() method which will emit a Deposit event in order to signal to an off-chain relayer to begin the cross-chain process.
   * This is the first method that should be called in order to bridge a price request to Mainnet.
   * @param ancillaryData extra data of price request.
   * @param identifier Identifier of price request.
   * @param time Timestamp of price request.
   */
  requestPrice: {
    (
      identifier: string,
      time: number | BN | string,
      ancillaryData: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      identifier: string,
      time: number | BN | string,
      ancillaryData: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      identifier: string,
      time: number | BN | string,
      ancillaryData: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      identifier: string,
      time: number | BN | string,
      ancillaryData: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * This method should basically check that the `Bridge.deposit()` was triggered by a valid price request, specifically one that has not resolved yet and was called by a registered contract. Without this check, `Bridge.deposit()` could be called by non-registered contracts to make price requests to the DVM.
   * This method will ultimately be called after `requestPrice` calls `Bridge.deposit()`, which will call `GenericHandler.deposit()` and ultimately this method.
   * @param ancillaryData extra data of price request.
   * @param identifier Identifier of price request.
   * @param sinkChainID Chain ID for this contract.
   * @param time Timestamp of price request.
   */
  validateDeposit: {
    (
      sinkChainID: number | BN | string,
      identifier: string,
      time: number | BN | string,
      ancillaryData: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      sinkChainID: number | BN | string,
      identifier: string,
      time: number | BN | string,
      ancillaryData: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      sinkChainID: number | BN | string,
      identifier: string,
      time: number | BN | string,
      ancillaryData: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      sinkChainID: number | BN | string,
      identifier: string,
      time: number | BN | string,
      ancillaryData: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * This method should publish the price data for a requested price request. If this method fails for some reason, then it means that the price was never requested. Can only be called by the `GenericHandler`.
   * This method will ultimately be called after a `publishPrice` has been bridged cross-chain from Mainnet to this network via an off-chain relayer. The relayer will call `Bridge.executeProposal` on this local network, which call `GenericHandler.executeProposal()` and ultimately this method.
   * @param ancillaryData extra data of price request to resolve.
   * @param identifier Identifier of price request to resolve.
   * @param price Price to publish to this oracle.
   * @param sinkChainID Chain ID for this contract.
   * @param time Timestamp of price request to resolve.
   */
  executePublishPrice: {
    (
      sinkChainID: number | BN | string,
      identifier: string,
      time: number | BN | string,
      ancillaryData: string,
      price: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      sinkChainID: number | BN | string,
      identifier: string,
      time: number | BN | string,
      ancillaryData: string,
      price: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      sinkChainID: number | BN | string,
      identifier: string,
      time: number | BN | string,
      ancillaryData: string,
      price: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      sinkChainID: number | BN | string,
      identifier: string,
      time: number | BN | string,
      ancillaryData: string,
      price: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  /**
   * Returns whether a price has resolved for the request.
   * @param ancillaryData extra data of price request.
   * @param identifier Identifier of price request.
   * @param time Timestamp of price request
   */
  hasPrice(
    identifier: string,
    time: number | BN | string,
    ancillaryData: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  /**
   * Reverts if price is not available.
   * Returns resolved price for the request.
   * @param ancillaryData extra data of price request.
   * @param identifier Identifier of price request.
   * @param time Timestamp of price request
   */
  getPrice(
    identifier: string,
    time: number | BN | string,
    ancillaryData: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  /**
   * More details about Resource ID's here: https://chainbridge.chainsafe.io/spec/#resource-id
   * Convenience method to get cross-chain Bridge resource ID linking this contract with the SourceOracle.
   */
  getResourceId(txDetails?: Truffle.TransactionDetails): Promise<string>;

  /**
   * GenericHandler.deposit() expects data to be formatted as:     len(data)                              uint256     bytes  0  - 32     data                                   bytes       bytes  32 - END
   * This helper method is useful for calling Bridge.deposit().
   * @param ancillaryData extra data of price request.
   * @param chainID Chain ID for this contract.
   * @param identifier Identifier of price request.
   * @param time Timestamp of price request.
   */
  formatMetadata(
    chainID: number | BN | string,
    identifier: string,
    time: number | BN | string,
    ancillaryData: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  methods: {
    currentChainID(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    destinationChainID(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    finder(txDetails?: Truffle.TransactionDetails): Promise<string>;

    /**
     * Can be called only by a Registered contract that is allowed to make DVM price requests. Will mark this price request as Requested, and therefore able to receive the ultimate price resolution data, and also calls the local Bridge's deposit() method which will emit a Deposit event in order to signal to an off-chain relayer to begin the cross-chain process.
     * This is the first method that should be called in order to bridge a price request to Mainnet.
     * @param ancillaryData extra data of price request.
     * @param identifier Identifier of price request.
     * @param time Timestamp of price request.
     */
    requestPrice: {
      (
        identifier: string,
        time: number | BN | string,
        ancillaryData: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        identifier: string,
        time: number | BN | string,
        ancillaryData: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        identifier: string,
        time: number | BN | string,
        ancillaryData: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        identifier: string,
        time: number | BN | string,
        ancillaryData: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * This method should basically check that the `Bridge.deposit()` was triggered by a valid price request, specifically one that has not resolved yet and was called by a registered contract. Without this check, `Bridge.deposit()` could be called by non-registered contracts to make price requests to the DVM.
     * This method will ultimately be called after `requestPrice` calls `Bridge.deposit()`, which will call `GenericHandler.deposit()` and ultimately this method.
     * @param ancillaryData extra data of price request.
     * @param identifier Identifier of price request.
     * @param sinkChainID Chain ID for this contract.
     * @param time Timestamp of price request.
     */
    validateDeposit: {
      (
        sinkChainID: number | BN | string,
        identifier: string,
        time: number | BN | string,
        ancillaryData: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        sinkChainID: number | BN | string,
        identifier: string,
        time: number | BN | string,
        ancillaryData: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        sinkChainID: number | BN | string,
        identifier: string,
        time: number | BN | string,
        ancillaryData: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        sinkChainID: number | BN | string,
        identifier: string,
        time: number | BN | string,
        ancillaryData: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * This method should publish the price data for a requested price request. If this method fails for some reason, then it means that the price was never requested. Can only be called by the `GenericHandler`.
     * This method will ultimately be called after a `publishPrice` has been bridged cross-chain from Mainnet to this network via an off-chain relayer. The relayer will call `Bridge.executeProposal` on this local network, which call `GenericHandler.executeProposal()` and ultimately this method.
     * @param ancillaryData extra data of price request to resolve.
     * @param identifier Identifier of price request to resolve.
     * @param price Price to publish to this oracle.
     * @param sinkChainID Chain ID for this contract.
     * @param time Timestamp of price request to resolve.
     */
    executePublishPrice: {
      (
        sinkChainID: number | BN | string,
        identifier: string,
        time: number | BN | string,
        ancillaryData: string,
        price: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        sinkChainID: number | BN | string,
        identifier: string,
        time: number | BN | string,
        ancillaryData: string,
        price: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        sinkChainID: number | BN | string,
        identifier: string,
        time: number | BN | string,
        ancillaryData: string,
        price: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        sinkChainID: number | BN | string,
        identifier: string,
        time: number | BN | string,
        ancillaryData: string,
        price: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    /**
     * Returns whether a price has resolved for the request.
     * @param ancillaryData extra data of price request.
     * @param identifier Identifier of price request.
     * @param time Timestamp of price request
     */
    hasPrice(
      identifier: string,
      time: number | BN | string,
      ancillaryData: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    /**
     * Reverts if price is not available.
     * Returns resolved price for the request.
     * @param ancillaryData extra data of price request.
     * @param identifier Identifier of price request.
     * @param time Timestamp of price request
     */
    getPrice(
      identifier: string,
      time: number | BN | string,
      ancillaryData: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    /**
     * More details about Resource ID's here: https://chainbridge.chainsafe.io/spec/#resource-id
     * Convenience method to get cross-chain Bridge resource ID linking this contract with the SourceOracle.
     */
    getResourceId(txDetails?: Truffle.TransactionDetails): Promise<string>;

    /**
     * GenericHandler.deposit() expects data to be formatted as:     len(data)                              uint256     bytes  0  - 32     data                                   bytes       bytes  32 - END
     * This helper method is useful for calling Bridge.deposit().
     * @param ancillaryData extra data of price request.
     * @param chainID Chain ID for this contract.
     * @param identifier Identifier of price request.
     * @param time Timestamp of price request.
     */
    formatMetadata(
      chainID: number | BN | string,
      identifier: string,
      time: number | BN | string,
      ancillaryData: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
