/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface BeaconOracleInterface extends ethers.utils.Interface {
  functions: {
    "currentChainID()": FunctionFragment;
    "finder()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "currentChainID",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "finder", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "currentChainID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "finder", data: BytesLike): Result;

  events: {
    "PriceRequestAdded(uint8,bytes32,uint256,bytes)": EventFragment;
    "PushedPrice(uint8,bytes32,uint256,bytes,int256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "PriceRequestAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PushedPrice"): EventFragment;
}

export class BeaconOracle extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: BeaconOracleInterface;

  functions: {
    currentChainID(overrides?: CallOverrides): Promise<[number]>;

    "currentChainID()"(overrides?: CallOverrides): Promise<[number]>;

    finder(overrides?: CallOverrides): Promise<[string]>;

    "finder()"(overrides?: CallOverrides): Promise<[string]>;
  };

  currentChainID(overrides?: CallOverrides): Promise<number>;

  "currentChainID()"(overrides?: CallOverrides): Promise<number>;

  finder(overrides?: CallOverrides): Promise<string>;

  "finder()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    currentChainID(overrides?: CallOverrides): Promise<number>;

    "currentChainID()"(overrides?: CallOverrides): Promise<number>;

    finder(overrides?: CallOverrides): Promise<string>;

    "finder()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    PriceRequestAdded(
      chainID: BigNumberish | null,
      identifier: BytesLike | null,
      time: null,
      ancillaryData: null
    ): TypedEventFilter<
      [number, string, BigNumber, string],
      {
        chainID: number;
        identifier: string;
        time: BigNumber;
        ancillaryData: string;
      }
    >;

    PushedPrice(
      chainID: BigNumberish | null,
      identifier: BytesLike | null,
      time: null,
      ancillaryData: null,
      price: null
    ): TypedEventFilter<
      [number, string, BigNumber, string, BigNumber],
      {
        chainID: number;
        identifier: string;
        time: BigNumber;
        ancillaryData: string;
        price: BigNumber;
      }
    >;
  };

  estimateGas: {
    currentChainID(overrides?: CallOverrides): Promise<BigNumber>;

    "currentChainID()"(overrides?: CallOverrides): Promise<BigNumber>;

    finder(overrides?: CallOverrides): Promise<BigNumber>;

    "finder()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    currentChainID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "currentChainID()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    finder(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "finder()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
