/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IDepositExecuteInterface extends ethers.utils.Interface {
  functions: {
    "deposit(bytes32,uint8,uint64,address,bytes)": FunctionFragment;
    "executeProposal(bytes32,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "deposit",
    values: [BytesLike, BigNumberish, BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeProposal",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeProposal",
    data: BytesLike
  ): Result;

  events: {};
}

export class IDepositExecute extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IDepositExecuteInterface;

  functions: {
    /**
     * It is intended that deposit are made using the Bridge contract.
     * @param data Consists of additional data needed for a specific deposit.
     * @param depositNonce This value is generated as an ID by the Bridge contract.
     * @param depositer Address of account making the deposit in the Bridge contract.
     * @param destinationChainID Chain ID deposit is expected to be bridged to.
     */
    deposit(
      resourceID: BytesLike,
      destinationChainID: BigNumberish,
      depositNonce: BigNumberish,
      depositer: string,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    /**
     * It is intended that deposit are made using the Bridge contract.
     * @param data Consists of additional data needed for a specific deposit.
     * @param depositNonce This value is generated as an ID by the Bridge contract.
     * @param depositer Address of account making the deposit in the Bridge contract.
     * @param destinationChainID Chain ID deposit is expected to be bridged to.
     */
    "deposit(bytes32,uint8,uint64,address,bytes)"(
      resourceID: BytesLike,
      destinationChainID: BigNumberish,
      depositNonce: BigNumberish,
      depositer: string,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    /**
     * It is intended that proposals are executed by the Bridge contract.
     * @param data Consists of additional data needed for a specific deposit execution.
     */
    executeProposal(
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    /**
     * It is intended that proposals are executed by the Bridge contract.
     * @param data Consists of additional data needed for a specific deposit execution.
     */
    "executeProposal(bytes32,bytes)"(
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  /**
   * It is intended that deposit are made using the Bridge contract.
   * @param data Consists of additional data needed for a specific deposit.
   * @param depositNonce This value is generated as an ID by the Bridge contract.
   * @param depositer Address of account making the deposit in the Bridge contract.
   * @param destinationChainID Chain ID deposit is expected to be bridged to.
   */
  deposit(
    resourceID: BytesLike,
    destinationChainID: BigNumberish,
    depositNonce: BigNumberish,
    depositer: string,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  /**
   * It is intended that deposit are made using the Bridge contract.
   * @param data Consists of additional data needed for a specific deposit.
   * @param depositNonce This value is generated as an ID by the Bridge contract.
   * @param depositer Address of account making the deposit in the Bridge contract.
   * @param destinationChainID Chain ID deposit is expected to be bridged to.
   */
  "deposit(bytes32,uint8,uint64,address,bytes)"(
    resourceID: BytesLike,
    destinationChainID: BigNumberish,
    depositNonce: BigNumberish,
    depositer: string,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  /**
   * It is intended that proposals are executed by the Bridge contract.
   * @param data Consists of additional data needed for a specific deposit execution.
   */
  executeProposal(
    resourceID: BytesLike,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  /**
   * It is intended that proposals are executed by the Bridge contract.
   * @param data Consists of additional data needed for a specific deposit execution.
   */
  "executeProposal(bytes32,bytes)"(
    resourceID: BytesLike,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    /**
     * It is intended that deposit are made using the Bridge contract.
     * @param data Consists of additional data needed for a specific deposit.
     * @param depositNonce This value is generated as an ID by the Bridge contract.
     * @param depositer Address of account making the deposit in the Bridge contract.
     * @param destinationChainID Chain ID deposit is expected to be bridged to.
     */
    deposit(
      resourceID: BytesLike,
      destinationChainID: BigNumberish,
      depositNonce: BigNumberish,
      depositer: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * It is intended that deposit are made using the Bridge contract.
     * @param data Consists of additional data needed for a specific deposit.
     * @param depositNonce This value is generated as an ID by the Bridge contract.
     * @param depositer Address of account making the deposit in the Bridge contract.
     * @param destinationChainID Chain ID deposit is expected to be bridged to.
     */
    "deposit(bytes32,uint8,uint64,address,bytes)"(
      resourceID: BytesLike,
      destinationChainID: BigNumberish,
      depositNonce: BigNumberish,
      depositer: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * It is intended that proposals are executed by the Bridge contract.
     * @param data Consists of additional data needed for a specific deposit execution.
     */
    executeProposal(
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * It is intended that proposals are executed by the Bridge contract.
     * @param data Consists of additional data needed for a specific deposit execution.
     */
    "executeProposal(bytes32,bytes)"(
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    /**
     * It is intended that deposit are made using the Bridge contract.
     * @param data Consists of additional data needed for a specific deposit.
     * @param depositNonce This value is generated as an ID by the Bridge contract.
     * @param depositer Address of account making the deposit in the Bridge contract.
     * @param destinationChainID Chain ID deposit is expected to be bridged to.
     */
    deposit(
      resourceID: BytesLike,
      destinationChainID: BigNumberish,
      depositNonce: BigNumberish,
      depositer: string,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    /**
     * It is intended that deposit are made using the Bridge contract.
     * @param data Consists of additional data needed for a specific deposit.
     * @param depositNonce This value is generated as an ID by the Bridge contract.
     * @param depositer Address of account making the deposit in the Bridge contract.
     * @param destinationChainID Chain ID deposit is expected to be bridged to.
     */
    "deposit(bytes32,uint8,uint64,address,bytes)"(
      resourceID: BytesLike,
      destinationChainID: BigNumberish,
      depositNonce: BigNumberish,
      depositer: string,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    /**
     * It is intended that proposals are executed by the Bridge contract.
     * @param data Consists of additional data needed for a specific deposit execution.
     */
    executeProposal(
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    /**
     * It is intended that proposals are executed by the Bridge contract.
     * @param data Consists of additional data needed for a specific deposit execution.
     */
    "executeProposal(bytes32,bytes)"(
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    /**
     * It is intended that deposit are made using the Bridge contract.
     * @param data Consists of additional data needed for a specific deposit.
     * @param depositNonce This value is generated as an ID by the Bridge contract.
     * @param depositer Address of account making the deposit in the Bridge contract.
     * @param destinationChainID Chain ID deposit is expected to be bridged to.
     */
    deposit(
      resourceID: BytesLike,
      destinationChainID: BigNumberish,
      depositNonce: BigNumberish,
      depositer: string,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    /**
     * It is intended that deposit are made using the Bridge contract.
     * @param data Consists of additional data needed for a specific deposit.
     * @param depositNonce This value is generated as an ID by the Bridge contract.
     * @param depositer Address of account making the deposit in the Bridge contract.
     * @param destinationChainID Chain ID deposit is expected to be bridged to.
     */
    "deposit(bytes32,uint8,uint64,address,bytes)"(
      resourceID: BytesLike,
      destinationChainID: BigNumberish,
      depositNonce: BigNumberish,
      depositer: string,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    /**
     * It is intended that proposals are executed by the Bridge contract.
     * @param data Consists of additional data needed for a specific deposit execution.
     */
    executeProposal(
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    /**
     * It is intended that proposals are executed by the Bridge contract.
     * @param data Consists of additional data needed for a specific deposit execution.
     */
    "executeProposal(bytes32,bytes)"(
      resourceID: BytesLike,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
